name: Hello World

on:
  workflow_dispatch

jobs:
  first-action:
    runs-on: ubuntu-latest
    environment:
      name: devEnvironment
    steps:
      - name: first command
        run: echo "Hii Master Kunal !"
  
  second-action:
  runs-on: ubuntu-latest
  steps:
    - name: test 2
      run: pwd
  
  third-action:
   runs-on: ubuntu-latest
   steps:
    - name: test 3
      run: ls -a