name: Actions

on: 
  push:
  pull_request:
    types: [closed,assigned,opened,reopened]  # added activity types

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/simple.yml

      
