name: shell commands

on: [workflow_call] 

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    environment:
      name: devEnvironment
    steps:
      - name: Called Workflow
        run: echo "Reused Workflow !"
      

# EOF 
